[package]
name = "unity-slot-desktop"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
winvd = { git = "https://github.com/Ciantic/VirtualDesktopAccessor.git", rev = "8172097993b1194e3d5e2ff38421ebb06f867b6c" }
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
] }
